services: docker
language: node_js
node_js:
  - 6
before_install:
  # Strips out dashes in organization names because they are not allowed in dockerhub
  - export DOCKER_REPO=`awk -F/ '{gsub("-","",$1)};{print $1"/"$2}' <<<$TRAVIS_REPO_SLUG | tr '[:upper:]' '[:lower:]'`
  - export IMAGE_SLUG="$TRAVIS_BRANCH.${TRAVIS_COMMIT::8}.${TRAVIS_BUILD_ID}"
  - docker -v
  - cp .env.example .env
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  # set env vars in the build settings to interact with repositories
  # see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # Start the docker stuff
  - docker-compose -v
  - docker-compose up -d
  - sleep 4
  # Build front-end assets
  - npm install production
  - docker-compose ps
  # Build cli container
  - docker build -t "${DOCKER_REPO}:cli" -f infrastructure/cli/Dockerfile .
install:
  # Install dev php dependencies
  - docker exec -it $(docker-compose ps -q fpm) sh -c "composer install --no-interaction --prefer-dist"
script:
  # Seed database
  - docker exec -it $(docker-compose ps -q fpm) sh -c "php artisan migrate --seed"
  # Run tests
  - docker exec -it $(docker-compose ps -q fpm) sh -c "vendor/bin/phpunit"
  # Clean up pre-packaged stuff so the Laravel instance is clean and re-run tests to make sure we didn't break something
  - docker exec -it $(docker-compose ps -q fpm) sh -c "php artisan clean:template -f"
  - docker exec -it $(docker-compose ps -q fpm) sh -c "vendor/bin/phpunit"
after_success:
  # Deployable image tags must be in format: [service].[branch].[commit-hash].[timestamp]
  - if [[ $TRAVIS_PULL_REQUEST = false && ($TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH == 'staging') ]]; then docker tag "${DOCKER_REPO}:fpm" "${DOCKER_REPO}:fpm.${IMAGE_SLUG}" && docker push "${DOCKER_REPO}:fpm.${IMAGE_SLUG}" ; fi
  - if [[ $TRAVIS_PULL_REQUEST = false && ($TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH == 'staging') ]]; then docker tag "${DOCKER_REPO}:cli" "${DOCKER_REPO}:cli.${IMAGE_SLUG}" && docker push "${DOCKER_REPO}:cli.${IMAGE_SLUG}" ; fi
  - if [[ $TRAVIS_PULL_REQUEST = false && ($TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH == 'staging') ]]; then docker tag "${DOCKER_REPO}:nginx" "${DOCKER_REPO}:nginx.${IMAGE_SLUG}" && docker push "${DOCKER_REPO}:nginx.${IMAGE_SLUG}" ; fi
after_script:
- docker images
notifications:
  slack:
    secure: ${SLACK_TOKEN}
